apiVersion: v1
kind: Service
metadata:
  name: {{ include "pii-shield-operator.fullname" . }}-metrics-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pii-shield-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "pii-shield-operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pii-shield-operator.fullname" . }}-webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pii-shield-operator.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "pii-shield-operator.selectorLabels" . | nindent 4 }}
